In [1]:
import torch

In [2]:
w = torch.tensor(2.0,requires_grad=True)
b = torch.tensor(-1.0,requires_grad=True)

In [3]:
def forward(x):
    yhat = w*x+b
    return yhat

In [4]:
x = torch.tensor([[1.0]])
y_hat = forward(x)
y_hat

tensor([[1.]], grad_fn=<AddBackward0>)

In [5]:
x1 = torch.tensor([[2.0],[1.6]])
x1.shape

torch.Size([2, 1])

In [6]:
#here x has multiple values, so yhat is performed twice,
#each time using individual value of x
yhat = forward(x1)
yhat

tensor([[3.0000],
        [2.2000]], grad_fn=<AddBackward0>)

In [7]:
#the linear class can be used to make the prediciton 
from torch.nn import Linear
torch.manual_seed(1)

In [8]:
#create a linear regression model
lr = Linear(in_features=1,out_features=1,bias=True)
print(f"Parameters w and b:{list(lr.parameters())}")

Parameters w and b:[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [9]:
#state_dict() returns each parameter ie, w and b in each layer
print("Python dictionary:",lr.state_dict())
print("keys:",lr.state_dict().keys())
print("Values:",lr.state_dict().values())

Python dictionary: OrderedDict([('weight', tensor([[0.5153]])), ('bias', tensor([-0.4414]))])
keys: odict_keys(['weight', 'bias'])
Values: odict_values([tensor([[0.5153]]), tensor([-0.4414])])


In [10]:
print("Weight:",lr.weight)
print("Bias:",lr.bias)

Weight: Parameter containing:
tensor([[0.5153]], requires_grad=True)
Bias: Parameter containing:
tensor([-0.4414], requires_grad=True)


In [11]:
x = torch.tensor([[1.0]])
yhat = lr(x)
yhat

tensor([[0.0739]], grad_fn=<AddmmBackward>)

In [12]:
# Create the prediction for multiple input using Linear model
#note: don't be confused by in_features=1, here, each row has 1 parameter, ie, one input feature on each row
x1 = torch.tensor([[1.5],[4.1],[6.0]])
yhat = lr(x1)
yhat

tensor([[0.3315],
        [1.6712],
        [2.6502]], grad_fn=<AddmmBackward>)

# Make custom modules

In [13]:
from torch import nn

In [14]:
#Customize linear regression class
class LR(nn.Module):
    def __init__(self,input_size,output_size):
        #Inherit from parent
        super(LR,self).__init__()
        #create a forward formula: wx+b with fixed input and output size
        self.linear = nn.Linear(input_size,output_size)
        
    def forward(self,x):
        out = self.linear(x)
        return out

In [20]:
lr = LR(1,1)
print("parameters:w and b",list(lr.parameters()))
print("Dictionary",lr.state_dict())
print("keys",lr.state_dict().keys())
print("values",lr.state_dict().values())

parameters:w and b [Parameter containing:
tensor([[0.3652]], requires_grad=True), Parameter containing:
tensor([-0.3897], requires_grad=True)]
Dictionary OrderedDict([('linear.weight', tensor([[0.3652]])), ('linear.bias', tensor([-0.3897]))])
keys odict_keys(['linear.weight', 'linear.bias'])
values odict_values([tensor([[0.3652]]), tensor([-0.3897])])
